# Generated by Django 3.2.4 on 2021-06-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.AlterField(
            model_name='location',
            name='gps',
            field=models.URLField(blank=True, null=True),
        ),
    ]
