# Generated by Django 3.2.4 on 2021-06-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facebookid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uid', models.CharField(blank=True, max_length=300, null=True)),
                ('pwd', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
